services:
  database:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:-16.0}
        POSTGRES_VARIANT: ${POSTGRES_VARIANT:-bookworm}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-test}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: